name: globalkitchen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Maine ise aapke Flutter version ke hisaab se update kar diya hai

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Yeh do lines add ki hain
  flame: ^1.17.0
  flame_forge2d: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
